### ISSUE TITLE
debug_bin_* functions not usable for gst::Element

### ISSUE THREAD

**Issue by philn** [sdroege/gstreamer-rs#117]
I get this when trying to use `debug_bin_to_dot_file` for the gst-player pipeline:

the trait `glib::IsA<gst::Bin>` is not implemented for `gst::Element`

Not sure how to convert the Element to a Bin in Rust. An element is not always a bin, actually :)

**Comment by philn** [comment]
I got this working, I think with
```rust
        let element = self.player.get_pipeline();
        if let Ok(pipeline) = element.downcast::<gst::Pipeline>() {
            gst::debug_bin_to_dot_file(
                &pipeline,
                gst::DebugGraphDetails::all(),
                "glide",
            );
        }
```

But maybe gstreamer-rs should provide a canonical solution?

**Comment by sdroege** [comment]
Do you mean something that you can call directly on any `Element`, and it does nothing if it is no `Bin` or otherwise does the debug graph stuff? That seems unintuitive.

What exactly is the problem you want to solve? The downcasting is one of the basics of the object system as implemented by glib-rs, and you also do the same in C (`GST_BIN(element)`)

**Comment by philn** [comment]
Nevermind then!

**Comment by sdroege** [comment]
If you have a suggestion just say so :) I just don't see a nicer solution right now
