### ISSUE TITLE
Add bindings for GstGL

### ISSUE THREAD

**Issue by ceyusa** [sdroege/gstreamer-rs#126]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gl.html

For the Servo context would be required a mean to share the gstglcontext/gstgldisplay and, perhaps, GstGLMemory.

**Comment by philn** [comment]
To get texture IDs you can map video frames with the `GST_MAP_GL` flag too.

**Comment by sdroege** [comment]
As a first step we would need -sys bindings for GL. And someone to decide on how to map OpenGL things to Rust. The lowest common denominator for the latter seems to be https://crates.io/crates/gl

It will also always be unsafe at the gstreamer-rs level as OpenGL is unsafe by itself. One can build safe layers on top with various libraries but I would prefer to keep things low-level here so that we can integrate with anything and everything later.

Are you planning to work on this? As a first step, try running the GstGL gir file through the code generator for generating -sys bindings. I expect there to be some fixes necessary, but I'd be happy to help if you have any questions.

**Comment by sdroege** [comment]
> To get texture IDs you can map video frames with the GST_MAP_GL flag too.

There are currently no bindings for `GstMemory` and if you mapped a `VideoFrame` with those flags currently then it would also not work well. The current `VideoFrame` bindings assume that the mapped data is a slice of the expected size. So those two parts would also need some work.

**Comment by Freyr666** [comment]
The main PITA is Gl types, I still didn't figure it out if it's GIR who should understand GL types or Gstreamer GL types should be coerced to Glib types.

**Comment by sdroege** [comment]
The main PITA will be GLs inherent unsafety later :) let's hope we can just build upon the gl crate here.

For the GL types, there is a GL-1.0.gir available for this. That should help bringing this a bit further. Some amounts of manual code will in any case be needed though

**Comment by ceyusa** [comment]
Servo uses [gleam](https://crates.io/crates/gleam) for barebone OpenGL bindings, and [glutin](https://crates.io/crates/glutin) to create and share(?) GL contexts

**Comment by sdroege** [comment]
This is now tracked at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/issues/126
