### ISSUE TITLE
Do callbacks need Sync?

### ISSUE THREAD

**Issue by Manishearth** [sdroege/gstreamer-rs#154]
Things like `webrtc.connect("on-negotiation-needed", callback)` have a `Sync` bound on the callback, which is only necessary if the callback is going to be invoked simultaneously on multiple threads. Is this ever the case? If not, can the bound be removed?

cc @sdroege

**Comment by sdroege** [comment]
The problem is that for the generic `connect` function we can't possibly know the constraints of the signal. That's why it has these strong bounds.

In case of the signal you mention, `Send` would be needed but `Sync` not. If it was part of normal, static API we could override that but unfortunately it's plugin API.

Either you'll have to add a `Mutex` or similar, or you could also `transmute` a non-`Sync` closure here to have the unneeded `Sync` bound. We could also add some kind of `connect_unsafe()` function that allows closures without `Send` and `Sync` bound to be passed, but that probably doesn't help you?

---

Unrelated, GitHub is only a mirror for the bindings now. Issues, etc. are at https://gitlab.freedesktop.org/gstreamer/gstreamer-rs :)
