### ISSUE TITLE
c2rust.com

### ISSUE THREAD

**Issue by mczarnek** [sdroege/gstreamer-rs#159]
I see that gstreamer is written in c itself. Have you ever considered instead of simply binding to Rust, you run the source code through [C2Rust - c2rust.com](https://c2rust.com/) and create a Rust version of Gstreamer?

Big plus: If you then compile the newly generated Rust code, you should instantly find any lingering memory safety issues as the Rust code won't compile those pieces. Little bit of Rust rewriting might be needed, but I'm sure the Rust community would be happy to help, love to see this, and you could both cross-advertise each other's projects a little bit.

Would be interesting to see how performance compares as well. Again, I bet if you run it by the Rust community they could even find a few ways to further optimize this using built in Rust functions. Make sure you run it through a performance profiler to find bottlenecks.

**Comment by sdroege** [comment]
I don't think c2rust would be a good starting point for porting the GStreamer GObject/C code. A better approach would probably be to either a) do it completely from scratch and updating API/concepts in a way that makes everything nicer in Rust, b) do it iteratively per "component" while keeping the GObject/C API and ideally ABI intact. I don't think c2rust can really help here.

However how useful that would be, I don't know. It would be a few months of effort just to port/rewrite the GStreamer core and that doesn't bring you most of the interesting functionality yet, just the basic infrastructure. And that part is actually relatively bug-free at this point, thanks to being a quite mature codebase.

Independent of that, to target all places where GStreamer is currently used there are a couple of things (related to ABI, building, shared libraries) that have to be solved on the Rust side first to make it a good choice in general.

So a better approach here at this point might be (and that's actually happening already to some degree) to write new functionality in Rust. GStreamer has most of its actually interesting functionality in plugins. That's also where most chances for bugs to exist are. It's possible to write GStreamer plugins in Rust already, and people are doing that. Doing so also has the advantage that any GStreamer application in any language can directly benefit from that and make use of new code written in Rust.

So if that's something you want to work on, go ahead, all you need is already there :) Also if you want to work on rewriting some existing components in Rust, feel free to do so as an experiment but it's unlikely that at the current time that would be integrated into GStreamer until the issues I shortly mentioned above are solved on the Rust side.

Closing this issue here for now as it's not really related to the bindings.
