### ISSUE TITLE
Tutorials don't work on macOS due to not running a NSRunLoop on the main thread, as required for OpenGL on macOS

### ISSUE THREAD

**Issue by pornel** [sdroege/gstreamer-rs#58]
```sh
gstreamer-rs/tutorials$ cargo run --bin basic-tutorial-1
```

> couldn't load TLS file database: Failed to open file '/Library/Frameworks/GStreamer.framework/Versions/1.0/etc/ssl/certs/ca-certificates.crt': No such file or directory

I've installed gstreamer-1.0-devel-1.12.3-x86_64.pkg, gstreamer-1.0-1.12.3-x86_64.pkg, and the dmg with a ton of installer packages (base-crypto-1.12.3-x86_64.pkg, base-system-1.0-1.12.3-x86_64.pkg, gstreamer-1.0-capture-1.12.3-x86_64.pkg, gstreamer-1.0-codecs-1.12.3-x86_64.pkg, gstreamer-1.0-codecs-gpl-1.12.3-x86_64.pkg, gstreamer-1.0-codecs-restricted-1.12.3-x86_64.pkg, gstreamer-1.0-core-1.12.3-x86_64.pkg, gstreamer-1.0-devtools-1.12.3-x86_64.pkg, gstreamer-1.0-dvd-1.12.3-x86_64.pkg, gstreamer-1.0-editing-1.12.3-x86_64.pkg, gstreamer-1.0-effects-1.12.3-x86_64.pkg, gstreamer-1.0-encoding-1.12.3-x86_64.pkg, gstreamer-1.0-libav-1.12.3-x86_64.pkg, gstreamer-1.0-net-1.12.3-x86_64.pkg, gstreamer-1.0-net-restricted-1.12.3-x86_64.pkg, gstreamer-1.0-playback-1.12.3-x86_64.pkg, gstreamer-1.0-system-1.12.3-x86_64.pkg, gstreamer-1.0-visualizers-1.12.3-x86_64.pkg, osx-framework-1.12.3-x86_64.pkg).

and yet, the directory "/Library/Frameworks/GStreamer.framework/Versions/1.0/etc/ssl/" is missing (there's only "fonts" in "etc").

**Comment by sdroege** [comment]
You should've installed gstreamer-1.0-1.12.3-x86_64.pkg and gstreamer-1.0-devel-1.12.3-x86_64.pkg, not all the little pieces from the .dmg file. It's supposed to be in the base-crypto package if you install the separate ones. Question is why the file does not exist in your case, someone on macOS would have to look into that so best report that here: https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer . It's a problem unrelated to the bindings.

----

Nonetheless, your problem is likely something different. That warning there is only a warning, and everything should continue just fine unless you try to use HTTPS/TLS. Which the first tutorial actually does, and because of that should cleanly error out but not hang forever.

My guess is that this is the same problem as https://github.com/sdroege/gstreamer-rs/issues/59 https://github.com/sdroege/gstreamer-rs/issues/60 and maybe https://github.com/sdroege/gstreamer-rs/issues/61

Can you run `target/debug/basic-tutorial-1` in gdb or lldb and check where it gets stuck? E.g.

```shell
lldb target/debug/basic-tutorial-1
run
[wait a bit and do ctrl+c]
thread backtrace all
```

And please do the same thing with `target/debug/basic-tutorial-2`, as that one does not use HTTPS/TLS or any network things.

Also please run `otool -L` on e.g. `target/debug/basic-tutorial-1` and paste the output. My best guess is that you link your Rust code to a different version of GLib than the GStreamer code is linked against.

Also do you have GStreamer installed via binaries *and* homebrew, or do you have glib installed also via homebrew?

**Comment by sdroege** [comment]
Also a debug log generated with `GST_DEBUG=6` set in the environment would be useful to have for all of these.

**Comment by philn** [comment]
I installed the 2 pkg files mentioned by Sebastian above, then set `PKG_CONFIG_PATH=/Library/Frameworks/GStreamer.framework/Libraries/pkgconfig/` and tutorial-1 starts but no video window appears because that example doesn't run a cocoa event loop.

However if you try the launch_glib_main example, it will work if you pass this as command line arguments: `playbin uri=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm`

**Comment by pornel** [comment]
So I did sudo rm -rf /Library/Frameworks/GStreamer.framework/ and re-installed only the two main .pkg installers, and now I have the `etc/ssl` folder.

**Comment by sdroege** [comment]
Great, but that doesn't solve the real problem here :)

**Comment by pornel** [comment]
After framework reinstall it is able to fetch https stream and plays it, but just like Tutorial 2, it doesn't display any video (should it?)

**Comment by sdroege** [comment]
Yes but that's broken on macOS currently (see https://github.com/sdroege/gstreamer-rs/issues/58#issuecomment-343733340). We would have to run a NSRunLoop on the main thread (probably? maybe some other thread also works), otherwise you can't use OpenGL on macOS (and various other things).

However adding that to the tutorial would make the tutorial quite a bit more complicated. You couldn't just pop messages from the bus anymore but would have to use a real event loop then.

**Comment by sdroege** [comment]
It's the same issue with the C tutorials btw

**Comment by pornel** [comment]
Oh, I've got it working!

```rust
#[link(name = "foundation", kind = "framework")]
extern "C" {
    fn CFRunLoopRun();
}

fn main() {
    std::thread::spawn(|| {
      // all example code here
    });

    unsafe {CFRunLoopRun();}
}
```

**Comment by andrewssobral** [comment]
Hello @kornelski , All, 

Sorry to comment is this old post, I saw your answer because I have the same problem. 
How you managed to compile this code with gcc?
```
#[link(name = "foundation", kind = "framework")]
extern "C" {
    fn CFRunLoopRun();
}

fn main() {
    std::thread::spawn(|| {
      // all example code here
    });

    unsafe {CFRunLoopRun();}
}
```


Before that, I managed to compile the basic-tutorial-1.c by:
```
 gcc basic-tutorial-1.c -o basic-tutorial-1 `pkg-config --cflags --libs gstreamer-1.0`
 ```
but when I run `./basic-tutorial-1` I got:
```
 zsh: illegal hardware instruction  ./basic-tutorial-1
```
Using lldb I have this:
```
% lldb ./basic-tutorial-1
(lldb) target create "./basic-tutorial-1"
Current executable set to '/Users/andrewssobral/Projects/gstreamer/basic-tutorial-1' (x86_64).
(lldb) target create "basic-tutorial-1"
Current executable set to '/Users/andrewssobral/Projects/gstreamer/basic-tutorial-1' (x86_64).
(lldb) run
Process 31509 launched: '/Users/andrewssobral/Projects/gstreamer/basic-tutorial-1' (x86_64)
2021-07-23 23:37:05.347908+0200 basic-tutorial-1[31509:2201654] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x109b0d040> F8BB1C28-BAE8-11D6-9C31-00039315CD46
Process 31509 stopped
* thread #12, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00007fff20789427 CoreFoundation`__CFRunLoopDeallocate.cold.1 + 14
CoreFoundation`__CFRunLoopDeallocate.cold.1:
->  0x7fff20789427 <+14>: ud2    
CoreFoundation`_CFRunLoopGet2.cold.1:
    0x7fff20789429 <+0>:  leaq   0x210856(%rip), %rax      ; "Foundation-only CFRunLoop function called without Foundation present"
    0x7fff20789430 <+7>:  movq   %rax, 0x603a5071(%rip)    ; gCRAnnotations + 8
    0x7fff20789437 <+14>: ud2    
Target 1: (basic-tutorial-1) stopped.
(lldb) quit
```

What kind of modifications I need to make in this code to make it works?
```
#include <gst/gst.h>

int
main (int argc, char *argv[])
{
  GstElement *pipeline;
  GstBus *bus;
  GstMessage *msg;

  /* Initialize GStreamer */
  gst_init (&argc, &argv);

  /* Build the pipeline */
  pipeline =
      gst_parse_launch
      ("playbin uri=https://www.freedesktop.org/software/gstreamer-sdk/data/media/sintel_trailer-480p.webm",
      NULL);

  /* Start playing */
  gst_element_set_state (pipeline, GST_STATE_PLAYING);

  /* Wait until error or EOS */
  bus = gst_element_get_bus (pipeline);
  msg =
      gst_bus_timed_pop_filtered (bus, GST_CLOCK_TIME_NONE,
      GST_MESSAGE_ERROR | GST_MESSAGE_EOS);

  /* Free resources */
  if (msg != NULL)
    gst_message_unref (msg);
  gst_object_unref (bus);
  gst_element_set_state (pipeline, GST_STATE_NULL);
  gst_object_unref (pipeline);
  return 0;
}
```

**Comment by kornelski** [comment]
That code is written in the Rust programming language, not C. GCC doesn't support Rust yet.

**Comment by andrewssobral** [comment]
@kornelski , All,

I was able to compile and run successfully the Basic tutorial 12: Streaming.
https://gstreamer.freedesktop.org/documentation/tutorials/basic/streaming.html?gi-language=c

**Comment by sdroege** [comment]
The correct place to report this would be https://gitlab.freedesktop.org/gstreamer/gst-docs/
