### ISSUE TITLE
Tutorial 3 & 4 on macOS: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

### ISSUE THREAD

**Issue by pornel** [sdroege/gstreamer-rs#60]
```sh
 cargo run --bin basic-tutorial-3
```

> (process:74622): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
> thread 'main' panicked at 'Can't set uri property on uridecodebin: BoolError("Invalid property name")', src/libcore/result.rs:906:4

backtrace points to `src/bin/basic-tutorial-3.rs:28`:

```rust
    source
        .set_property("uri", &uri)
        .expect("Can't set uri property on uridecodebin");
```

**Comment by sdroege** [comment]
See https://github.com/sdroege/gstreamer-rs/issues/58#issuecomment-343722297 , it might be the same problem. This warning usually only happens if you have two different versions of GLib in your process.

Also please set `G_DEBUG=fatal_warnings` in the environment, and run the application in lldb. Then give a backtrace of all threads (see the other comment) once it stops. It will stop on the `pool != NULL` warning.

**Comment by philn** [comment]
Also duplicate of #58

**Comment by pornel** [comment]
Yup, my installation was cursed. It runs after reinstall of gstreamer.
