### ISSUE TITLE
Bug in GStreamer, mark MessageRef::get_src() unsafe?

### ISSUE THREAD

**Issue by rikte88** [sdroege/gstreamer-rs#81]
When running a playbin, It turns out that messages exist on the bus where the message src pointer is invalid. (already freed or something)

Checking if msg.get_src() == pipeline sometimes causes memory corruption that will crash the program at a later time.

This is of course not a problem with this excellent library, but possibly MessageRef::get_src() should be unsafe with a warning until this gets fixed in GStreamer?

This is the reason for the bug that i filed earlier:
https://github.com/sdroege/gstreamer-rs/issues/70

I managed to work around this limitation in the following way:

```
// let msg_from_pipeline = msg.get_src().unwrap() == pipeline; // DON'T DO THIS
let msg_from_pipeline = unsafe { // WORKAROUND
  use glib::translate::ToGlibPtr;
  use gstreamer_sys::{GstElement, GstPipeline};
  let pipeline_ptr: *const GstPipeline = pipeline.to_glib_none().0;
  let msg_src_ptr = (*msg.as_ptr()).src as *const GstElement;
  pipeline_ptr as *const GstElement == msg_src_ptr
};
```
With the workaround, all problems go away and it works flawlessly.

Tested on Fedora 27 with:
[karlri@localhost ~]$ gst-launch-1.0 --version
gst-launch-1.0 version 1.12.4
GStreamer 1.12.4
http://download.fedoraproject.org

**Comment by sdroege** [comment]
This is a bug in GStreamer and has to be fixed there. The first issue that you reported before is already fixed since a while and you can ask your distro to backport the fix for that, the second one is something I couldn't reproduce (and I asked some questions about that, which you never replied to).

From your workaround and problem description, it's either still that bug that is fixed since a while in GStreamer (and your version doesn't have the fix included), or from somewhere else a message is created with a source that is still a floating reference (or some other reference counting bug). In case of the latter I would be very interested in further details, as asked in your other ticket a while ago.


The function itself is not unsafe, there only seems to be a bug in your version of GStreamer and that has to be fixed. There's no point in marking this safe function as unsafe just because there are some interactions between different GStreamer plugins that can cause problems, otherwise we could as well mark the whole GStreamer bindings as unsafe :) You could always install a GStreamer plugin that could cause various functions calls of the bindings to cause memory corruption related crashes or other unsafeties. Similarly, if e.g. glibc has a memory unsafety bug, nobody would argue that all possible Rust API should be marked unsafe on that platform.
